# Generated by Django 2.1 on 2018-08-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmonitor', '0004_auto_20180830_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionhistory',
            name='result_text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='query',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
